// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkiUWXkHMw5yjl5YafT83ABbC_MDaIc6M',
    appId: '1:80459686537:android:ed9322b1c6273cf0781c58',
    messagingSenderId: '80459686537',
    projectId: 'easyfit-330e5',
    authDomain: 'easyfit-330e5.firebaseapp.com',
    storageBucket: 'easyfit-330e5.appspot.com',
    measurementId: 'G-YJBE9Z9Z88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkiUWXkHMw5yjl5YafT83ABbC_MDaIc6M',
    appId: '1:80459686537:android:ed9322b1c6273cf0781c58',
    messagingSenderId: '80459686537',
    projectId: 'easyfit-330e5',
    storageBucket: 'easyfit-330e5.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyBYylDX1hPosVPA3Gh7odvcOWg_lekaOhU',
  //   appId: '1:471079441847:ios:c743fbc88be374716f4432',
  //   messagingSenderId: '471079441847',
  //   projectId: 'easy-fit-5e643',
  //   storageBucket: 'easy-fit-5e643.appspot.com',
  //   iosClientId: '471079441847-j0md8rg953p21ap9t1hm5o4hvq79ccct.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.easyfit',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyBYylDX1hPosVPA3Gh7odvcOWg_lekaOhU',
  //   appId: '1:471079441847:ios:c743fbc88be374716f4432',
  //   messagingSenderId: '471079441847',
  //   projectId: 'easy-fit-5e643',
  //   storageBucket: 'easy-fit-5e643.appspot.com',
  //   iosClientId: '471079441847-j0md8rg953p21ap9t1hm5o4hvq79ccct.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.easyfit',
  // );
}
